### ISSUE TITLE
(Feature Request) Add option to remove lasers that cover video screen

### ISSUE THREAD

**Issue by CalaMariGold** [Kevga/BeatSaberCinema#1]
For many maps, there are those lasers directly in the center that cover the screen and really ruin the experience. I was wondering if there could be an option to remove those lasers specifically, or move them somewhere else?

Other than that, this mod is amazing. Thanks!

**Comment by Kevga** [comment]
Thank you for the suggestion. I agree about those lasers being a bit in the way. I'll see what I can do about them.

**Comment by Kevga** [comment]
Addressed in commit 7aa8097. I will close this after I release a build that includes this commit, please keep it open until then.

Before:
![image](https://user-images.githubusercontent.com/9109613/101622341-3737e180-3a17-11eb-89ab-8c31de958fd4.png)

After:
![image](https://user-images.githubusercontent.com/9109613/101622391-46b72a80-3a17-11eb-87ce-c5ef23d591f0.png)
