### ISSUE TITLE
[Feature Request] Pass "--ignore-config" parameter to youtube-dl

### ISSUE THREAD

**Issue by xtex404** [Kevga/BeatSaberCinema#11]
## Quick summary

The "--ignore-config" flag should be passed to youtube-dl.exe so it doesn't use the %APPDATA%\youtube-dl\config.txt file I use for everyday things.

## Details

I have a youtube-dl config file for everyday use, which is incompatible with the parameters BeatSaberCinema uses. The bundled youtube-dl.exe happily opens that config and tries to use those parameters, which causes the mod to fail without any sort of indication why. Took me a while to figure out it was my own config breaking it. Adding "--ignore-config" right around line 389 of DownloadController.cs will fix that. (it seemed dumb to fork/patch/push/etc for this so... I didn't. Hope that's okay.)

Great mod, btw.. love it. :)

**Comment by Kevga** [comment]
Thank you, good suggestion. Instead of outright ignoring the config I'll probably use the ```--config-location``` option, so users can still use a custom config specifically for Cinema.
