### ISSUE TITLE
Any possibility to put this mod on quest?

### ISSUE THREAD

**Issue by Osin** [Kevga/BeatSaberCinema#12]
## Quick summary
I would love to see this feature on my oculus quest

## Details
Please describe the feature as accurately as possible.
Is it possible to setup custom mod thanks to bmbf. But if is it possible to add this mod from, i will really appreciate.
Maybe some people are like me and are waiting for it from too long time. If is it possible from your part, i hope you would not hesitate to give us a feedback about. 

Thanks

**Comment by Kevga** [comment]
Unfortunately I don't have a Quest myself, so it would be almost impossible for me to develop for it. That said, I heard from the Quest modders that it can be a bit difficult to access the Unity VideoPlayer class on Quest, which Cinema for PC relies on for video playback. Under the current circumstances it's not feasible for me to attempt porting it to Quest.
