### ISSUE TITLE
Video not playing at all

### ISSUE THREAD

**Issue by PnfrlEnm** [Kevga/BeatSaberCinema#13]
Every time I try to play a song with a video, the video just isn't there. The environment changes / moves as if there's a video playing, but there's no video (it may be black, but either way it doesn't show up). The game is also a slight bit laggier when there's supposed to be a video playing. There's also no audio in the preview mode, and the video there shows up, but it just plays the first few frames and then completely freezes.

[_latest.log](https://github.com/Kevga/BeatSaberCinema/files/6216468/_latest.log)

**Comment by Kevga** [comment]
From the BSIPA log you attached I see nothing indicating what's going wrong.

Could you do the following:
1) Try to preview a video again, if possible a different one not in the WIP folder this time just to make sure
2) Start the song, wait for it to start
3) Quit the game, press `Win+R`, paste `%userprofile%\appdata\locallow\Hyperbolic Magnetism\Beat Saber` and press Enter
4) Attach the file called `Player.log` from the Explorer window that opens

That's the log file that Unity creates, video playback errors end up in there.

**Comment by PnfrlEnm** [comment]
First song (BLACKPINK - Kill This Love) I played the full level but didn't preview in the menu
Second song (Madeon - The Prince) I only previewed the video in the menu

[Player.log](https://github.com/Kevga/BeatSaberCinema/files/6216721/Player.log)

**Comment by Kevga** [comment]
And just to make sure, the behavior was the same? Video not playing during gameplay and freezing in the preview? Does any video start playing when you select the level?

The second log didn't show any issues with video playback either, so I'm really not sure where the problem could be. You could try temporarily moving some other mods out of the Plugins folder to check if it's some sort of incompatibility with another mod.

**Comment by PnfrlEnm** [comment]
The behavior is the exact same. I'll play around with my mods and see if I can find one that's causing an issue.

**Comment by Kevga** [comment]
By pure chance I was able to reproduce the issue after I tried out the CAS ReShade tool that was posted on BSMG. The Unity video player component seemingly just refuses to play any video (and audio) when ReShade is installed. Do you also happen to use something that injects post-process effects into Beat Saber?

**Comment by PnfrlEnm** [comment]
Lo and behold, I _am_ using ReShade :/
