### ISSUE TITLE
Searching for a song video always results in nothing found. 

### ISSUE THREAD

**Issue by TheOneAce** [Kevga/BeatSaberCinema#14]
Originally worked, crashed my beat saber when looking for a video and when I reloaded the game it always says nothing found when searching for a video to add.

[_latest.log](https://github.com/Kevga/BeatSaberCinema/files/6240016/_latest.log)

**Comment by Kevga** [comment]
Thanks for reporting this. YouTube changed something on their end a few hours ago which necessitates an update of youtube-dl. The new version is now available in ModAssistant, so please update your mods using that.

**Comment by TheOneAce** [comment]
Sorted, thank you.
