### ISSUE TITLE
youtube-dl Needs updating

### ISSUE THREAD

**Issue by Heronickproductions** [Kevga/BeatSaberCinema#15]
Version Cinema 1.4.1.
had the problem that all videos failed to download.
when i downloaded the most recent version of youtube-dl 2021.04.01 it worked again

**Comment by xedlock** [comment]
launch modassistant and hit "install or update"... the youtube-dl library was updated there to the 2021.4.1 version a few days ago. :)

**Comment by Heronickproductions** [comment]
> launch modassistant and hit "install or update"... the youtube-dl library was updated there to the 2021.4.1 version a few days ago. :)

o sorry my mistake

**Comment by Kevga** [comment]
I will publish a new build soon so that the GitHub release doesn't come with an outdated youtube-dl. For now you can update youtube-dl via ModAssistant, as xedlock said.
