### ISSUE TITLE
Problem downloading videos

### ISSUE THREAD

**Issue by Dooglesmile** [Kevga/BeatSaberCinema#16]
## 1. Bug description
When I open the song browser section in Beat Saber and choose the cinema playlist, it gives me the option to download videos for the songs in the list, but when I click to download, it shows the 'downloading' message, then stops.
The game also freezes up after a few moments too. Today it froze up totally and I had to force the game closed.

For songs not in the playlist it doesn't even attempt to search for a video clip for them, no matter what keywords I use.

I've included the last two log files below.

I installed the latest version 1.4.1 from ModAssistant before trying this today.

## 2. BSIPA log
[INFO @ 18:57:54 | Cinema] BeatSaberCinema enabled
[INFO @ 19:01:16 | Cinema] Starting youtube-dl process with arguments: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" "ytsearch10:Dance Monkey - Tones and I" -j -i
[ERROR @ 19:01:18 | Cinema] youtube-dl process error:
[ERROR @ 19:01:18 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 19:01:18 | Cinema] Search process exited with exitcode 1
[INFO @ 19:01:27 | Cinema] Starting youtube-dl process with arguments: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" "ytsearch10:Dance Monkey - Tones and I" -j -i
[ERROR @ 19:01:28 | Cinema] youtube-dl process error:
[ERROR @ 19:01:28 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 19:01:28 | Cinema] Search process exited with exitcode 1
[INFO @ 19:01:42 | Cinema] Starting youtube-dl process with arguments: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" "ytsearch10:dance monkey" -j -i
[ERROR @ 19:01:43 | Cinema] youtube-dl process error:
[ERROR @ 19:01:43 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 19:01:43 | Cinema] Search process exited with exitcode 1
[INFO @ 19:01:54 | Cinema] Starting youtube-dl process with arguments: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" "ytsearch10:No Nimbus - Scroobius Pip" -j -i
[ERROR @ 19:01:56 | Cinema] youtube-dl process error:
[ERROR @ 19:01:56 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 19:01:56 | Cinema] Search process exited with exitcode 1
[INFO @ 19:02:11 | Cinema] Starting youtube-dl process with arguments: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" "ytsearch10:scroobius pip" -j -i
[ERROR @ 19:02:12 | Cinema] youtube-dl process error:
[ERROR @ 19:02:12 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 19:02:12 | Cinema] Search process exited with exitcode 1
[INFO @ 19:02:25 | Cinema] Starting youtube-dl process with arguments: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" "ytsearch10:Shut Up and Dance - WALK THE MOON" -j -i
[ERROR @ 19:02:26 | Cinema] youtube-dl process error:
[ERROR @ 19:02:26 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 19:02:26 | Cinema] Search process exited with exitcode 1
[INFO @ 19:02:35 | Cinema] Starting youtube-dl process with arguments: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" "ytsearch10:Shut Up and Dance - WALK THE MOON" -j -i
[ERROR @ 19:02:36 | Cinema] youtube-dl process error:
[ERROR @ 19:02:36 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 19:02:36 | Cinema] Search process exited with exitcode 1
[INFO @ 19:02:57 | Cinema] Starting youtube-dl process with arguments: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" "ytsearch10:$100 Bills - Jaroslav Beck" -j -i
[ERROR @ 19:02:58 | Cinema] youtube-dl process error:
[ERROR @ 19:02:58 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 19:02:58 | Cinema] Search process exited with exitcode 1
[INFO @ 19:03:00 | Cinema] Starting youtube-dl process with arguments: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" "ytsearch10:$100 Bills - Jaroslav Beck" -j -i
[ERROR @ 19:03:01 | Cinema] youtube-dl process error:
[ERROR @ 19:03:01 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 19:03:01 | Cinema] Search process exited with exitcode 1
[INFO @ 19:03:04 | Cinema] Starting youtube-dl process with arguments: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" "ytsearch10:Beat Saber - Jaroslav Beck" -j -i
[ERROR @ 19:03:05 | Cinema] youtube-dl process error:
[ERROR @ 19:03:05 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 19:03:05 | Cinema] Search process exited with exitcode 1
[INFO @ 19:03:30 | Cinema] Starting download of 【BOFU2017】もぺもぺ
[INFO @ 19:03:30 | Cinema] youtube-dl command: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" https://www.youtube.com/watch?v=nC-bVtpIMd4 -f "bestvideo[height<=1080][vcodec*=avc1]+bestaudio[acodec*=mp4]" --no-cache-dir -o "【BOFU2017】もぺもぺ.%(ext)s" --no-playlist --no-part --recode-video mp4 --no-mtime --socket-timeout 10 --no-continue
[ERROR @ 19:03:31 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 19:03:34 | Cinema] Starting download of 【BOFU2017】もぺもぺ
[INFO @ 19:03:34 | Cinema] youtube-dl command: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" https://www.youtube.com/watch?v=nC-bVtpIMd4 -f "bestvideo[height<=1080][vcodec*=avc1]+bestaudio[acodec*=mp4]" --no-cache-dir -o "【BOFU2017】もぺもぺ.%(ext)s" --no-playlist --no-part --recode-video mp4 --no-mtime --socket-timeout 10 --no-continue
[ERROR @ 19:03:35 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 19:03:36 | Cinema] Starting download of 【BOFU2017】もぺもぺ
[INFO @ 19:03:36 | Cinema] youtube-dl command: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" https://www.youtube.com/watch?v=nC-bVtpIMd4 -f "bestvideo[height<=1080][vcodec*=avc1]+bestaudio[acodec*=mp4]" --no-cache-dir -o "【BOFU2017】もぺもぺ.%(ext)s" --no-playlist --no-part --recode-video mp4 --no-mtime --socket-timeout 10 --no-continue
[ERROR @ 19:03:37 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 19:03:42 | Cinema] Starting download of 【BOFU2017】もぺもぺ
[INFO @ 19:03:42 | Cinema] youtube-dl command: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" https://www.youtube.com/watch?v=nC-bVtpIMd4 -f "bestvideo[height<=1080][vcodec*=avc1]+bestaudio[acodec*=mp4]" --no-cache-dir -o "【BOFU2017】もぺもぺ.%(ext)s" --no-playlist --no-part --recode-video mp4 --no-mtime --socket-timeout 10 --no-continue
[ERROR @ 19:03:43 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 19:03:45 | Cinema] Saving video config to J:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\129bf (Mope Mope - waika)\cinema-video.json
[INFO @ 19:03:46 | Cinema] Starting download of Marnik - Up & Down (Official Video)
[INFO @ 19:03:46 | Cinema] youtube-dl command: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" https://www.youtube.com/watch?v=oJa7Kr7_9dw -f "bestvideo[height<=1080][vcodec*=avc1]+bestaudio[acodec*=mp4]" --no-cache-dir -o "Marnik - Up & Down (Official Video).%(ext)s" --no-playlist --no-part --recode-video mp4 --no-mtime --socket-timeout 10 --no-continue
[ERROR @ 19:03:47 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 19:03:49 | Cinema] Saving video config to J:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\2aa85aad10e124eb674d18d49251bc94ee1a4283\cinema-video.json
[INFO @ 19:04:03 | Cinema] Saving video config to J:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\2aa85aad10e124eb674d18d49251bc94ee1a4283\cinema-video.json
[INFO @ 19:04:16 | Cinema] Saving video config to J:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\129bf (Mope Mope - waika)\cinema-video.json
[INFO @ 19:04:19 | Cinema] Saving video config to J:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\2aa85aad10e124eb674d18d49251bc94ee1a4283\cinema-video.json
[INFO @ 19:04:27 | Cinema] Saving video config to J:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\129bf (Mope Mope - waika)\cinema-video.json
[INFO @ 19:04:36 | Cinema] Saving video config to J:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\2aa85aad10e124eb674d18d49251bc94ee1a4283\cinema-video.json
[INFO @ 19:04:58 | Cinema] Saving video config to J:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\2aa85aad10e124eb674d18d49251bc94ee1a4283\cinema-video.json
[INFO @ 19:04:58 | Cinema] Saving video config to J:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\2aa85aad10e124eb674d18d49251bc94ee1a4283\cinema-video.json
[INFO @ 19:04:58 | Cinema] Saving video config to J:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\2aa85aad10e124eb674d18d49251bc94ee1a4283\cinema-video.json
[INFO @ 19:04:59 | Cinema] Saving video config to J:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\129bf (Mope Mope - waika)\cinema-video.json
[INFO @ 19:04:59 | Cinema] Saving video config to J:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\129bf (Mope Mope - waika)\cinema-video.json
[INFO @ 19:05:11 | Cinema] Saving video config to J:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\129bf (Mope Mope - waika)\cinema-video.json
[INFO @ 19:06:00 | Cinema] BeatSaberCinema disabled

[INFO @ 17:52:32 | Cinema] BeatSaberCinema enabled
[INFO @ 17:53:07 | Cinema] Starting youtube-dl process with arguments: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" "ytsearch10:Dance Monkey - Tones and I" -j -i
[ERROR @ 17:53:10 | Cinema] youtube-dl process error:
[ERROR @ 17:53:10 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 17:53:10 | Cinema] Search process exited with exitcode 1
[INFO @ 17:53:15 | Cinema] Starting download of 【BOFU2017】もぺもぺ
[INFO @ 17:53:15 | Cinema] youtube-dl command: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" https://www.youtube.com/watch?v=nC-bVtpIMd4 -f "bestvideo[height<=720][vcodec*=avc1]+bestaudio[acodec*=mp4]" --no-cache-dir -o "【BOFU2017】もぺもぺ.%(ext)s" --no-playlist --no-part --recode-video mp4 --no-mtime --socket-timeout 10 --no-continue
[ERROR @ 17:53:16 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 17:53:20 | Cinema] Starting download of 【BOFU2017】もぺもぺ
[INFO @ 17:53:20 | Cinema] youtube-dl command: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" https://www.youtube.com/watch?v=nC-bVtpIMd4 -f "bestvideo[height<=720][vcodec*=avc1]+bestaudio[acodec*=mp4]" --no-cache-dir -o "【BOFU2017】もぺもぺ.%(ext)s" --no-playlist --no-part --recode-video mp4 --no-mtime --socket-timeout 10 --no-continue
[ERROR @ 17:53:21 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 17:53:26 | Cinema] Starting download of 【BOFU2017】もぺもぺ
[INFO @ 17:53:26 | Cinema] youtube-dl command: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" https://www.youtube.com/watch?v=nC-bVtpIMd4 -f "bestvideo[height<=720][vcodec*=avc1]+bestaudio[acodec*=mp4]" --no-cache-dir -o "【BOFU2017】もぺもぺ.%(ext)s" --no-playlist --no-part --recode-video mp4 --no-mtime --socket-timeout 10 --no-continue
[ERROR @ 17:53:28 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 17:53:28 | Cinema] Starting download of 【BOFU2017】もぺもぺ
[INFO @ 17:53:28 | Cinema] youtube-dl command: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" https://www.youtube.com/watch?v=nC-bVtpIMd4 -f "bestvideo[height<=720][vcodec*=avc1]+bestaudio[acodec*=mp4]" --no-cache-dir -o "【BOFU2017】もぺもぺ.%(ext)s" --no-playlist --no-part --recode-video mp4 --no-mtime --socket-timeout 10 --no-continue
[ERROR @ 17:53:29 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 17:53:32 | Cinema] Saving video config to J:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\129bf (Mope Mope - waika)\cinema-video.json
[INFO @ 17:53:33 | Cinema] Starting download of Marnik - Up & Down (Official Video)
[INFO @ 17:53:33 | Cinema] youtube-dl command: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" https://www.youtube.com/watch?v=oJa7Kr7_9dw -f "bestvideo[height<=720][vcodec*=avc1]+bestaudio[acodec*=mp4]" --no-cache-dir -o "Marnik - Up & Down (Official Video).%(ext)s" --no-playlist --no-part --recode-video mp4 --no-mtime --socket-timeout 10 --no-continue
[ERROR @ 17:53:35 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 17:53:41 | Cinema] Saving video config to J:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\2aa85aad10e124eb674d18d49251bc94ee1a4283\cinema-video.json
[INFO @ 17:53:43 | Cinema] Starting download of PSY - GANGNAM STYLE(강남스타일) M/V
[INFO @ 17:53:43 | Cinema] youtube-dl command: "J:\SteamLibrary\steamapps\common\Beat Saber\Libs\youtube-dl.exe" https://www.youtube.com/watch?v=9bZkp7q19f0 -f "bestvideo[height<=720][vcodec*=avc1]+bestaudio[acodec*=mp4]" --no-cache-dir -o "PSY - GANGNAM STYLE(강남스타일) M_V.%(ext)s" --no-playlist --no-part --recode-video mp4 --no-mtime --socket-timeout 10 --no-continue
[ERROR @ 17:53:44 | Cinema] ERROR: batch file batch-file.txt could not be read
[INFO @ 17:53:52 | Cinema] Saving video config to J:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\141 (Gangnam Style - GreatYazer)\cinema-video.json

**Comment by Kevga** [comment]
The error message makes it seem like you may have a global youtube-dl config stored somewhere that is breaking things. Coincidentally, the next release will ignore the global youtube-dl config, which would solve this issue for you if that is indeed the cause. Could you test the attached preview build of 1.4.2, to see if this fixes the issue?

[Cinema-1.4.2-rc1.zip](https://github.com/Kevga/BeatSaberCinema/files/6259799/Cinema-1.4.2-rc1.zip)

**Comment by Dooglesmile** [comment]
That worked, thank you.

I can now download videos both from songs in the cinema playlist and searching for my own videos for other songs I have, plus the freeze/crash seems to have gone too.

**Comment by Kevga** [comment]
Great, I'm glad it works for you now. Thanks for reporting back. I'll investigate the freezing, that shouldn't be happening, even if there is a problem with youtube-dl.
