### ISSUE TITLE
After previewing songs going to the credits the song video plays in the credits

### ISSUE THREAD

**Issue by 0Human0** [Kevga/BeatSaberCinema#17]
First go to an song preview the video go to the main menu then go to help and then click credits and the video you played in the preview will be in the credits.

https://user-images.githubusercontent.com/56775824/114259863-30a68000-999f-11eb-9d74-52c70fb9b8a4.mp4

**Comment by Kevga** [comment]
Thanks for reporting this. Fixed for next release.
