### ISSUE TITLE
Download cancelled 

### ISSUE THREAD

**Issue by Harry-Edwards** [Kevga/BeatSaberCinema#18]
Hi,

I've been trying to download the music video for the song Montero, but whenever I do, it starts, doesn't leave 0% and just says download cancelled, and I'm not sure why. 
When it says the download is cancelled, I'm not even doing anything, I don't press anything, nothing. 

Is there a fix? 
Thanks Harry

**Comment by Kevga** [comment]
Is this the only video that fails to download, or do you have issues with others, too? Make sure your youtube-dl is up-to-date by updating your mods with ModAssistant. If this doesn't fix your issue, I will need a log file from you.
