### ISSUE TITLE
Video does not play after playing a level

### ISSUE THREAD

**Issue by CraftMaster163** [Kevga/BeatSaberCinema#2]
I play a level with a video or without does not matter but next time I play a level with a video it does not play
Mod Log
[_latest.log](https://github.com/Kevga/BeatSaberCinema/files/5677668/_latest.log)
Game Log
[_latest.log](https://github.com/Kevga/BeatSaberCinema/files/5677671/_latest.log)

**Comment by Kevga** [comment]
After some troubleshooting over Discord we determined the cause to be a hardware issue.
