### ISSUE TITLE
Videos Download but don't play

### ISSUE THREAD

**Issue by fudydudyford** [Kevga/BeatSaberCinema#20]
Whenever I download music videos it shows the video in the background at first but once I go to another level and come back or play the level it stops working. I don't have any interfering mods and It's enabled so I have no idea why it isn't working. I have reinstalled beat saber and all of my mods and it still is not working.

My Logs (I used Ain't Got Rhythm from Phineas and Ferb):
[INFO @ 19:59:54 | Cinema] BeatSaberCinema enabled
[INFO @ 20:00:48 | Cinema] Loading video: C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\3237 (Ain't Got Rhythm - Phineas and Ferb - OfficialMemeGuy)\Ain't Got Rhythm  _ Phineas and Ferb _ Disney XD.mp4
[INFO @ 20:00:53 | Cinema] Loading video: C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\3237 (Ain't Got Rhythm - Phineas and Ferb - OfficialMemeGuy)\Ain't Got Rhythm  _ Phineas and Ferb _ Disney XD.mp4
[ERROR @ 20:00:53 | Cinema] Video player error: VideoPlayer cannot play url : C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\3237 (Ain't Got Rhythm - Phineas and Ferb - OfficialMemeGuy)\Ain't Got Rhythm  _ Phineas and Ferb _ Disney XD.mp4
[ERROR @ 20:00:53 | Cinema] Cannot read file.
[INFO @ 20:00:58 | Cinema] Starting youtube-dl process with arguments: "C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Libs\youtube-dl.exe" "ytsearch10:Ain't Got Rhythm - Phineas and Ferb - Phineas and Ferb" -j -i
[INFO @ 20:01:00 | Cinema] Loading video: C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\3237 (Ain't Got Rhythm - Phineas and Ferb - OfficialMemeGuy)\Ain't Got Rhythm  _ Phineas and Ferb _ Disney XD.mp4
[ERROR @ 20:01:00 | Cinema] Video player error: VideoPlayer cannot play url : C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\3237 (Ain't Got Rhythm - Phineas and Ferb - OfficialMemeGuy)\Ain't Got Rhythm  _ Phineas and Ferb _ Disney XD.mp4
[ERROR @ 20:01:00 | Cinema] Unexpected error code (10).
[INFO @ 20:01:02 | Cinema] Starting youtube-dl process with arguments: "C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Libs\youtube-dl.exe" "ytsearch10:Ain't Got Rhythm - Phineas and Ferb - Phineas and Ferb" -j -i
[INFO @ 20:01:09 | Cinema] Search process exited with exitcode 0
[INFO @ 20:01:10 | Cinema] Starting download of Ain't Got Rhythm  | Phineas and Ferb | Disney XD
[INFO @ 20:01:10 | Cinema] youtube-dl command: "C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Libs\youtube-dl.exe" https://www.youtube.com/watch?v=KTdFszcZp-I -f "bestvideo[height<=720][vcodec*=avc1]+bestaudio[acodec*=mp4]" --no-cache-dir -o "Ain't Got Rhythm  _ Phineas and Ferb _ Disney XD.%(ext)s" --no-playlist --no-part --recode-video mp4 --no-mtime --socket-timeout 10 --no-continue
[INFO @ 20:01:13 | Cinema] Download process exited with code 0
[INFO @ 20:01:13 | Cinema] Download finished
[INFO @ 20:01:13 | Cinema] Loading video: C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\3237 (Ain_t Got Rhythm - Phineas and Ferb - OfficialMemeGuy)\Ain't Got Rhythm  _ Phineas and Ferb _ Disney XD.mp4
[ERROR @ 20:01:13 | Cinema] Video player error: VideoPlayer cannot play url : C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\3237 (Ain_t Got Rhythm - Phineas and Ferb - OfficialMemeGuy)\Ain't Got Rhythm  _ Phineas and Ferb _ Disney XD.mp4
[ERROR @ 20:01:13 | Cinema] Unexpected error code (10).
[INFO @ 20:01:15 | Cinema] Overwriting environment to Big Mirror
[INFO @ 20:01:16 | Cinema] Saving video config to C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\3237 (Ain_t Got Rhythm - Phineas and Ferb - OfficialMemeGuy)\cinema-video.json
[INFO @ 20:01:18 | Cinema] Saving video config to C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\3237 (Ain_t Got Rhythm - Phineas and Ferb - OfficialMemeGuy)\cinema-video.json
[ERROR @ 20:01:21 | Cinema] Video player error: VideoPlayer cannot play url : C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\3237 (Ain_t Got Rhythm - Phineas and Ferb - OfficialMemeGuy)\Ain't Got Rhythm  _ Phineas and Ferb _ Disney XD.mp4
[ERROR @ 20:01:21 | Cinema] Unexpected error code (10).
[INFO @ 20:01:30 | Cinema] Saving video config to C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\3237 (Ain_t Got Rhythm - Phineas and Ferb - OfficialMemeGuy)\cinema-video.json
[INFO @ 20:01:30 | Cinema] Loading video: C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\3237 (Ain_t Got Rhythm - Phineas and Ferb - OfficialMemeGuy)\Ain't Got Rhythm  _ Phineas and Ferb _ Disney XD.mp4
[ERROR @ 20:01:30 | Cinema] Video player error: VideoPlayer cannot play url : C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\3237 (Ain_t Got Rhythm - Phineas and Ferb - OfficialMemeGuy)\Ain't Got Rhythm  _ Phineas and Ferb _ Disney XD.mp4
[ERROR @ 20:01:30 | Cinema] Cannot read file.
[INFO @ 20:01:50 | Cinema] Saving video config to C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\3237 (Ain_t Got Rhythm - Phineas and Ferb - OfficialMemeGuy)\cinema-video.json
[INFO @ 20:01:54 | Cinema] BeatSaberCinema disabled

**Comment by Kevga** [comment]
Can you reproduce the issue again and then post the Unity log (`Player.log`) at `%userprofile%\appdata\locallow\Hyperbolic Magnetism\Beat Saber` (you can paste this path into the Windows Explorer address bar)? Just drag & drop the whole file here, you don't need to copy and paste the contents. That log file contains more information about playback errors.  

And just to make sure, this happens with every map that has a video?

**Comment by fudydudyford** [comment]
It happens with every map

[Player.log](https://github.com/Kevga/BeatSaberCinema/files/6307546/Player.log)

**Comment by Kevga** [comment]
The error code when it first errors is this `0x887a0005`. According to the [documentation](https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/dxgi-error), this error is `DXGI_ERROR_DEVICE_REMOVED`, which may point to a crash of the graphics driver.

I remember issue #2 having the very same problem. In that person's case, there were other issues with their system which made them replace their mainboard. After that, the videos played fine. That does not mean that your mainboard is faulty, too, of course, but my suspicion is still that there's something wrong with some part of your system, be it software or hardware.

**Comment by fudydudyford** [comment]
I'm pretty sure it's not a hardware issue. I already reinstalled my graphics drivers and that didn't work. what should I do now?

**Comment by Kevga** [comment]
Are you using Windows 7? If so, this issue in Unity could be related: https://issuetracker.unity3d.com/issues/windows-7-windowsvideomedia-error-0xc00d36b4-error-is-thrown-when-loading-a-video-with-the-videoplayer. 

If that's the cause, there's not much we can do about it other than to wait for a fix in Unity and then for Beat Saber to update to a fixed version of Unity. Or update to Windows 10 I guess.

**Comment by fudydudyford** [comment]
no, I'm using windows 10

**Comment by Kevga** [comment]
Since the video plays fine at first and only fails starting with the second playback, maybe not stopping the video player after playback makes a difference. Try out this build, which does not explicitly stop the video player. I doubt it makes much of a difference, since I assume the video player calls stop implicitly when switching to a different video, but it's the only thing I could think of trying. The reality is that Cinema only tells the Unity video player to load a video file and then tells it to start and stop. If playback fails, the issue is likely somewhere on a lower level.

[Cinema-1.4.3-test.zip](https://github.com/Kevga/BeatSaberCinema/files/6310733/Cinema-1.4.3-test.zip)
