### ISSUE TITLE
[Feature Request] Filtering Supported Songs?

### ISSUE THREAD

**Issue by livejamie** [Kevga/BeatSaberCinema#21]
It's nice that a playlist is included but it would be nice if there was some way to filter out songs in my library that have a video ready to go.

Thanks!

**Comment by Kevga** [comment]
I'd rather try to avoid adding my own filter UI to an already cluttered song list, but I may be able to extend the filter options of SongBrowser to achieve this. I'll look into it.

**Comment by livejamie** [comment]
That would be perfect thanks :)
