### ISSUE TITLE
Videos not downloading fully in 720p and 1080p

### ISSUE THREAD

**Issue by Erik-97** [Kevga/BeatSaberCinema#3]
Hi!

I tried to download some videos but only 480p works, i waited like 5 mins then i opened the level folder and seems half of the video are missing and not continuing to download...

![download](https://user-images.githubusercontent.com/47022164/102019642-f6bcc880-3d74-11eb-9aaa-245ff17fa525.png)

**Comment by Kevga** [comment]
Thank you for reporting this issue. Can you try the new release I published and let me know if this fixed the problem for you?
https://github.com/Kevga/BeatSaberCinema/releases/tag/1.1.1

**Comment by Erik-97** [comment]
Tested 5 songs and works great, now i can see the download percentage too, before this it was stuck on 0%

**Comment by Kevga** [comment]
That's great to hear! Your screenshot helped me connect the dots and figure out that this was an issue related to different language settings in Windows. So, thanks again for the issue report.
