### ISSUE TITLE
Videos immediately "Cancelling" upon click

### ISSUE THREAD

**Issue by Crussy** [Kevga/BeatSaberCinema#31]
## 1. Bug description
Fresh install of both Oculus and Beat Saber on a brand new system. Used Mod Assistant to install Cinema and other requirements. Trying to download videos results in an immediate "Cancelling" and never downloads. Tried on several songs. Opened Mod Assistant and reinstalled mods. Same result. Opened Mod Assistant and installed ALL mods. Same result. Log attached.

## 2. BSIPA log
[_latest.log](https://github.com/Kevga/BeatSaberCinema/files/6977530/_latest.log)

**Comment by Kevga** [comment]
Try installing [Visual C++ 2010 Redist](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe). It's required for youtube-dl to run and some people's systems seem to be missing it.

**Comment by Crussy** [comment]
> Try installing [Visual C++ 2010 Redist](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe). It's required for youtube-dl to run and some people's systems seem to be missing it.

This fixed the issue. It all seems to be working correctly now!
