### ISSUE TITLE
Video not showing

### ISSUE THREAD

**Issue by GuWoSch** [Kevga/BeatSaberCinema#36]
Kevga, videos are not showing in game. Adjusting when the video starts (left audio channel) does not play the sound either. I can play the video outside of Beat Saber from the downloaded location fine.  I did reinstall Cinema by downloading the latest from GitHub.

> Cinema is enabled in the main menu settings
> I don't use 'ReShade'
> The video is downloaded in the below pasted error message location 

[ERROR @ 08:59:38 | Cinema] Video player error: VideoPlayer cannot play url : E:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\CinemaOSTVideos\POP_STARS - K_DA\K_DA - POP_STARS (ft_ Madison Beer, (G)I-DLE, Jaira Burns) _ Music Video - League of Legends.mp4
[ERROR @ 08:59:38 | Cinema] Unexpected error code (10).

[_latest.log](https://github.com/Kevga/BeatSaberCinema/files/7273658/_latest.log)

..am certain it's something on my system (otherwise others would have the same problem). Thanks for any tips :)

GuWoSch

**Comment by Kevga** [comment]
This looks to be the same issue as #30
