### ISSUE TITLE
Hard to set offset + Bug with Introskip

### ISSUE THREAD

**Issue by HitGub-Shiro** [Kevga/BeatSaberCinema#4]
Cause of both sources of sound being played in both ears during preview maybe a option to change the offset in the Pause menu? That would help cause you can see the changes.

Now to the bug when using the introskip button, well the Video doesnt skip. Thats pretty much it xD
Still no idea how to fix this though. 

Anyways still a really nice mod ^^

**Comment by Kevga** [comment]
Each sound source is played *mostly* in one ear. You only have to line up the sound, which is way easier to do than using visual cues in the video. If the sound lines up in the menu, the video should be in sync when you play the song. Let me know if that's not the case for you.

That issue with the Intro Skip mod should be fixable, I think the mod that enhances the practice mode should be affected by this issue, too. I personally don't use either so I didn't think of this. I'll take a look at it.

By the way, usually it's better to create multiple issues on GitHub if you have unrelated problems. No worries though.

**Comment by HitGub-Shiro** [comment]
Just wanted to add that it would be more easy if it only would be one ear, maybe its just me but I can only hear if its wrong or right but not rather i have to raise or lower the offset. I would like it more if it would be possible within the pause menu, but yeah your mod and stuff, just for not as it is its hard for me to set the offset. Or maybe even a option just to listen to the map sound and just sync to the video, that would also work better in my opinion. The Idea is good but the fact that the sound is mixed on the ear makes it hard.
