### ISSUE TITLE
Old versions has slow download speeds

### ISSUE THREAD

**Issue by LosWheatleynDew** [Kevga/BeatSaberCinema#43]
On older versions of the game (1.16.3 for me) downloads on cinema has been throttled to 528kilobits per second while in the latest it downloads it to my bandwidth [16mbps).
It happens only when i try to download the video in an old version of the game
[2021.11.03.16.22.53.log](https://github.com/Kevga/BeatSaberCinema/files/7471303/2021.11.03.16.22.53.log)

**Comment by Kevga** [comment]
I just published a [new release](https://github.com/Kevga/BeatSaberCinema/releases/tag/1.4.14) here on GitHub which should fix the slow download speeds. I didn't test it on older versions of the game, but it likely works fine on 1.16.3.
