### ISSUE TITLE
Why backlight makes video transparent?

### ISSUE THREAD

**Issue by nanikit** [Kevga/BeatSaberCinema#44]
## Reproducible steps
[log paste](https://pastebin.com/rr8YZMWv)
1. Download [this beatmap](https://beatsaver.com/maps/1ac0f).
2. In cinema configuration download [p.h. / Nekomata Okayu【Hololive】Romaji/English Lyrics](https://www.youtube.com/watch?v=ZVUBc2YbZeQ)
3. Play E+ difficulty.

## Expected behavior
Show the following without transparency.
![image](https://user-images.githubusercontent.com/4188984/147388030-52e84446-fc8d-4688-b372-e00a968b9b76.png)

## Actual behavior
![image](https://user-images.githubusercontent.com/4188984/147388006-42365a81-62c9-4b06-982a-f065b37be13c.png)

**Comment by Kevga** [comment]
This is not related to transparency, those spikes are in front of the screen. The screen is being partially covered. The real issue seems to be that the screen is positioned too far up, it should be more centered by default on that environment.
