### ISSUE TITLE
Beatsaber 1.19 cinema 1.4.16 not showing videos

### ISSUE THREAD

**Issue by XxTWMLxX** [Kevga/BeatSaberCinema#45]
## 1. Bug description
I have beatsaber 1.19 for htc vive. i have cinema installed and it is on with the slider. Reshade is not installed. I can download the videos for the songs, but when playing the song no video shows up.

## 2. BSIPA log
log attached.
[_latest.log](https://github.com/Kevga/BeatSaberCinema/files/7973170/_latest.log)

**Comment by Kevga** [comment]
Could you try this build and let me know if this fixes it? If not, please attach another log. Thank you!

[BeatSaberCinema.zip](https://github.com/Kevga/BeatSaberCinema/files/7973505/BeatSaberCinema.zip)

**Comment by XxTWMLxX** [comment]
I got it working shortly after posting this. Doing the same thing I already did. Some reason just worked. I deleted and redownload BSIPA from github and not the modassistant.... manually ran ipa.exe once then launched/closed the game. Working after that. Must of been an issue with BSIPA. 

Nothing seems wrong with cinema. 

All fixed up. Thank you for the reply.
