### ISSUE TITLE
Advanced settings dos not work

### ISSUE THREAD

**Issue by SPYNX0** [Kevga/BeatSaberCinema#47]
Adding any advanced settings on my song make nothing, when i start a map, there is no any video, and after deleting any advanced settings, video came back, i would like to use Additional screens, but can't get it working.

You should add a feature in-game to add  additionals screens, position and size, to make it easier ! 
[_latest.log](https://github.com/Kevga/BeatSaberCinema/files/8227293/_latest.log)
.

**Comment by Kevga** [comment]
Your config contains mistakes. You can use a json validator to check for errors.
