### ISSUE TITLE
No video playback through proton (Linux)

### ISSUE THREAD

**Issue by WiredG1** [Kevga/BeatSaberCinema#51]
Bug description
Videos download but don't play in linux(When running through proton)
Seems to be either a permission or playback error

Steps to reproduce:
1. Start steamVR
2. Start beat saber
3. Play a song with a video(note: you will have to press download every time you restart the game, hinting at cinema being unable to read from disk, hence a possible permission issue)
4. There will be no video

Attached log:
[_latest.log](https://github.com/Kevga/BeatSaberCinema/files/8602942/_latest.log)

**Comment by Kevga** [comment]
I recently got my Steam Deck so I thought it might be fun to take a look into this.

One issue that I ran into (that also seems to be the cause of your issue) is that the ffmpeg installation from the mod manager fails silently. It gets reported as installed, the manifest is installed correctly, but the actual executable is missing. Your logs indicate that the same may have happened on your system.

After I manually placed the executable of ffmpeg from the GitHub release of the mod into the Libs folder, I was able to download videos and they also showed up in game. However, the rendering seems to be broken, I'm just getting artifacting on the screen. I attached an image of how it looks like on my Steam Deck. I don't think this is something I can fix, as that probably relies on Proton being able to handle the Microsoft Media Foundation that Unity uses on Windows builds for video rendering.

![image](https://user-images.githubusercontent.com/9109613/172025674-12ec2c7e-c28e-4787-9a07-dc24fa93266d.png)

**Comment by smirgol** [comment]
I had similar issues. While I had the ffmpeg.exe file in Libs, it lacked any access permissions - it downloaded video and audio, but wasn't able to merge them into a single file. After adding them, I got the garbled video. I then switched to GE-Proton7-26 and all is cool.

**Comment by WiredG1** [comment]
I have now solved this issue for me at least.
Ffmepg was installed through beataroni automatically(but said failed)
I could locate the ffmepg.exe file in my libs folder. I simply changed the permissions for the file so programs could use it. (I just gave everyone full access to the file)
After this everything works perfectly
Using newest proton beta and beat Saber version.
