### ISSUE TITLE
[Mod Confliction] Cinema and BetterSongSearch

### ISSUE THREAD

**Issue by Auros** [Kevga/BeatSaberCinema#52]
## 1. Bug description
The most recent version of [BetterSongSearch](https://github.com/kinsi55/BeatSaber_BetterSongSearch) implemented a feature where song audio is previewed before the map is downloaded in it's UI. If the last selected map in a level selection menu is a cinema map with video previews in the menu on, then someone goes to BetterSongSearch's menu, it will play the last selected video every single time someone selects on a song.

## 2. BSIPA log
(No relevant logs or exceptions, not including)

**Comment by Kevga** [comment]
Thanks for reporting!
