### ISSUE TITLE
Play the sound of the video instead of Beat Saber

### ISSUE THREAD

**Issue by Wind-Yi** [Kevga/BeatSaberCinema#54]
I mean, the sound with video will be blocked.
How can I hear it?

and →→ only hear it.

**Comment by Kevga** [comment]
What's the use case for this? Why would you want this?

**Comment by Wind-Yi** [comment]
> What's the use case for this? Why would you want this?

I want to listen to some second creation of music. But now, I've solved it, I just replace the original sound source.
