### ISSUE TITLE
Cinema is not working for 1.21.0. 

### ISSUE THREAD

**Issue by SirenGlitch** [Kevga/BeatSaberCinema#55]
I have tried downloading from mod assistant, and beatmods.com, but it still doesn't work, it appears in the mods tab of the modifiers menu but says "unable to load gameplay tab". It doesn't appear in mod settings or the thing showing mods on the left of the main menu. Also maps that have it as a suggestion say its not there but it is installed in my plugins folder. Please help.
[_latest.log](https://github.com/Kevga/BeatSaberCinema/files/9403064/_latest.log)

**Comment by Kevga** [comment]
If you want to stay on game version 1.21 then Cinema 1.5.2 is the last release that supports that. I can guarantee you though that other mods will also cause you problems.

I recommend you update to the latest game version. All your installed mods will still work.
