### ISSUE TITLE
Cinema gameplay tab fails to load

### ISSUE THREAD

**Issue by rk-exxec** [Kevga/BeatSaberCinema#59]
When trying to play a cinema map, the Cinema gameplay tab on the left fails to load.

[_latest.log](https://github.com/Kevga/BeatSaberCinema/files/9766928/_latest.log)

**Comment by Kevga** [comment]
Beat Saber versions below 1.22.1 are no longer supported starting with Cinema 1.6.0. If you want to stay on game version 1.21, head to the releases page and download an earlier version of the mod. That incompatible versions appear on ModAssistant is a flaw with how the mod repository works, and over time you'll have the same issue with more mods than just Cinema.

**Comment by rk-exxec** [comment]
Ah, sorry about that. Thank you for the info! The BeatMods site is indeed somewhat confusing in that regard, as it shows the latest compatible version as 1.21
