### ISSUE TITLE
add external configuration file for youtube-dl

### ISSUE THREAD

**Issue by MaxLuchs** [Kevga/BeatSaberCinema#6]
Hello,

can you please adapt the program so that youtube-dl uses an external configuration file?

That would be good for configuring youtube-dl without the need to change the program anymore for specific youtube-dl settings.

**Comment by MaxLuchs** [comment]
https://github.com/ytdl-org/youtube-dl/blob/master/README.md#configuration

**Comment by MaxLuchs** [comment]
does already work. can put a config file for youtube-dl into home dir

**Comment by Kevga** [comment]
In case someone else has a similar request in the future and finds this, here's the documentation for how to add custom command line parameters to all youtube-dl commands:  
https://github.com/ytdl-org/youtube-dl#configuration
