### ISSUE TITLE
Cant download

### ISSUE THREAD

**Issue by CarfunkledFlip1** [Kevga/BeatSaberCinema#63]
when i try to download a video i just get an error that says "youtube error. See log for details" I have checked the faq and i have everything required downloaded and installed

Heres the log
[INFO @ 22:06:16 | Cinema] Starting download of PSY - GANGNAM STYLE(강남스타일) M/V
[INFO @ 22:06:16 | Cinema] youtube-dl command: "D:\SteamLibrary\steamapps\common\Beat Saber\Libs\yt-dlp.exe" https://www.youtube.com/watch?v=9bZkp7q19f0 -f "bestvideo[height<=720][vcodec*=avc1]+bestaudio[acodec*=mp4]" --no-cache-dir -o "D:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\141 (greatyazer - Gangnam Style)\PSY - GANGNAM STYLE(강남스타일) M_V.mp4" --no-playlist --no-part --recode-video mp4 --no-mtime --socket-timeout 10 --ignore-config
[ERROR @ 22:06:20 | Cinema] ERROR: [youtube] 9bZkp7q19f0: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[INFO @ 22:06:20 | Cinema] [31836] Download process exited with code 1
[INFO @ 22:06:20 | Cinema] Cancelled download
[INFO @ 22:06:20 | Cinema] Deleted video at D:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\141 (greatyazer - Gangnam Style)\PSY - GANGNAM STYLE(강남스타일) M_V.mp4
[INFO @ 22:06:26 | Cinema] Saving video config to D:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\141 (greatyazer - Gangnam Style)\cinema-video.json

**Comment by Kevga** [comment]
YouTube made a change that necessitates an update of yt-dlp. It is currently waiting for approval to be included in Mod Assistant.

In the meantime, you can download it directly from here:
https://github.com/yt-dlp/yt-dlp/releases/tag/2023.02.17
Choose `yt-dlp.exe` and place it in `Beat saber\Libs` and downloads will work again.
