### ISSUE TITLE
Cinema video download error

### ISSUE THREAD

**Issue by TheDutchSlayer** [Kevga/BeatSaberCinema#69]
Last few weeks more and more and now its almost 100% of the time, can't download videos inside the game anymore.
Every time want to download the video it tries for a second and then it says "error could not download video see log for details".
Looked at my user data folder but could not find the log for cinema.

I'm on beat saber 1.29.1 steam version.

Maybe its a youtube API thing?

**Comment by Kevga** [comment]
See the pinned issue #68
