### ISSUE TITLE
[Feature Request] Play custom video files not on youtube

### ISSUE THREAD

**Issue by Emberfire** [Kevga/BeatSaberCinema#71]
## Quick summary
It would be nice to have the option of placing a video file in the song folder, linking it in the `cinema-video.json` and playing it while ingame. Currently only youtube videos are supported, even if you manually edit the JSON.

**Comment by Kevga** [comment]
Did you read the section in the readme about it? What issue did you have when editing the json?
https://github.com/Kevga/BeatSaberCinema#playing-local-files-not-found-on-youtube

**Comment by Emberfire** [comment]
Now I feel embarrassed...

Sorry for opening this ticket, I seem to have missed this section. However, when I tried to manually edit the json the song in question (the ogre indeed :) ) just started without any video, though I simply deleted the ID property instead of setting it to an empty string. I will try this way and see if it works.

Sorry for bothering you
