### ISSUE TITLE
Null Reference

### ISSUE THREAD

**Issue by TinnyTerr** [Kevga/BeatSaberCinema#73]
## 1. Bug description
Game crashes instantly on startup. Had this issue multiple times, unknown if those are related to cinema as I had verified files and it resolved however this did not work this time. Game still does not launch after removing cinema but I believe that this is one of the causes. Log on line 585-586 has this error:
```
[CRITICAL @ 20:05:34 | UnityEngine] NullReferenceException: Object reference not set to an instance of an object
[CRITICAL @ 20:05:34 | UnityEngine] BeatSaberCinema.PlaybackController.OnDestroy () (at <09facce9b6b64834b5cc11c8301ef690>:0)
```
## 2. BSIPA log
[_latest.log](https://github.com/Kevga/BeatSaberCinema/files/14672076/_latest.log)

**Comment by Kevga** [comment]
The crash is unrelated to Cinema and the exception is no cause for concern. If you have a Discord account, you can get support for your issue in BSMG's pc-help channel.
