### ISSUE TITLE
A way to select which resolution of YT video to download

### ISSUE THREAD

**Issue by aceadamuk** [Kevga/BeatSaberCinema#8]
Would be a great if it would choose the best resolution version of that video or have an option within to mod to pick a Max res setting such as 1080p or 4k video etc. 

What a fantastic mod this is. Not seen till now. the Preview and Adjusting to get the video synced with the video is great and being able to download any video to the song is also a great addition.

**Comment by Kevga** [comment]
You can choose the video resolution in the settings on the left side of the main menu. It defaults to 720p so you don't have to wait too long for the download. 4K is not supported yet due to limitations of the Unity video player.

**Comment by aceadamuk** [comment]
cheers ill have a look later on :)
